version: '3'

services:
  event-master-meta:
    image: event-master-meta:1.0.0-meta
    container_name: event-master-meta
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8899:8080'
    volumes:
      - ./data:/src/main/resources